/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nao-ur' at '17/05/07 16:00' with Gradle 3.0
 *
 * @author nao-ur, @date 17/05/07 16:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
